name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the main branch
    paths:
      - "**.html"  # Runs only when an HTML file is changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV  # Generates a unique tag based on timestamp

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t jayakrishnasuddapalli/nginx-app:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image
        run: docker push jayakrishnasuddapalli/nginx-app:${{ env.IMAGE_TAG }}

      - name: Update Deployment File with New Tag
        run: |
          sed -i 's|image: jayakrishnasuddapalli/nginx-app:.*|image: jayakrishnasuddapalli/nginx-app:${{ env.IMAGE_TAG }}|' deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deployment.yaml
          git commit -m "Updated deployment image tag to ${{ env.IMAGE_TAG }}"
          git push origin main
