name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the main branch
    paths:
      - "**.html"  # Runs only when an HTML file is changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/nginx-app:latest .

      - name: Push Docker Image
        run: docker push your-dockerhub-username/nginx-app:latest

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/nginx-deployment nginx=your-dockerhub-username/nginx-app:latest --record
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
